[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/notify"
  to = "/.netlify/functions/notify"
  status = 200

[[headers]]
  for = "/OneSignalSDKWorker.js"
  [headers.values]
    Service-Worker-Allowed = "/"
    Cache-Control = "no-cache, no-store, must-revalidate"
